---
title: "Installation Procedures"
output: html_document
---
___
# MySQL Setup

>In order for the functions to work properly, you must create all the proper tables in a MySQL database. 

*Bold columns are the primary key of the table.*

***

<details> 
<summary><h3>MySQL Tables</h3></summary>
<br> 

### bot_channels

- **guild_id | VARCHAR(30)**
- channel_id | VARCHAR(30)

***

### guild_roles

- **unique_id | VARCHAR(60)**
- name | VARCHAR(45)
- guild_id | VARCHAR(30)
- emoji | VARAHCAR(45)

***

### level_guilds

- **guild_id | VARCHAR(30)**

***

### mod_channels

- **guild_id | VARCHAR(30)**
- channel_id | VARCHAR(30)

***

### punishment_table

- **punishments | VARCHAR(300)**
- guild_id | VARCHAR(30)

***

### reaction_messages

- **message_id | VARCHAR(30)**
- guild_id | VARCHAR(30)
- channel_id | VARCHAR(30)

***

### rpsrecord
- **player_combined_id | VARCHAR(60)**
- player_1_id | VARCHAR(30)
- player_2_id | VARCHAR(30)
- player_1_display_name | VARCHAR(45)
- player_2_display_name | VARCHAR(45)
- p1_points | INT(11)
- p2_points | INT(11)
- ties | INT(11)
- last_time_played | VARCHAR(45)
- guild_id | VARCHAR(30)

***

### saved_messages

- **message_id | VARCHAR(30)**
- display_name | VARCHAR(45)
- message_contents | VARCHAR(300)
- guild_id | VARCHAR(30)
- user_id | VARCHAR(30)
- saving_user_id | VARCHAR(30)

***

### stalker_table

- **unique_id | VARCHAR(75)**
- user_id | VARCHAR(30)
- tracked_user_id | VARCHAR(30)
- guild_id | VARCHAR(30)

***

### userdata

- **user_mention | VARCHAR(30)**
- user_display_name | VARCHAR(30)
- user_id | VARCHAR(30)
- time_modified | VARCHAR(20)
- guild_id | VARCHAR(30)

***

### userinfo

- **unique_id | VARCHAR(60)**
- time | VARCHAR(45)
- display_name | VARCHAR(45)
- mention | VARCHAR(30)
- points | INT(11)
- level | INT(11)
- guild_id | VARCHAR(30)
- notification | TINYINT(1)

</details>

***

<h1>Code Setup</h1>


>In order for the bot to properly connect to the MySQL database, you must change 
>the USER, DATABASE, HOST, and PASSWORD variables 
>in lines 17-20 to that of the MySQL database previously set up. 